# Generated by Django 6.0.3 on 2026-03-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_url', models.URLField(help_text='URL do post do Instagram (ex: https://www.instagram.com/p/XXXXX/)', max_length=500)),
                ('caption', models.CharField(blank=True, help_text='Legenda opcional', max_length=255)),
                ('thumbnail', models.ImageField(blank=True, help_text='Imagem de thumbnail (opcional, caso o embed não carregue)', upload_to='instagram/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'post do Instagram',
                'verbose_name_plural': 'posts do Instagram',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
