# Generated by Django 6.0.3 on 2026-03-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do membro da equipa', max_length=255)),
                ('role', models.CharField(help_text='Cargo / Função', max_length=255)),
                ('photo', models.ImageField(help_text='Foto do membro', upload_to='team/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'membro da equipa',
                'verbose_name_plural': 'membros da equipa',
                'ordering': ['order', 'name'],
            },
        ),
    ]
