# Generated by Django 6.0.3 on 2026-03-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_teammember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstagramPost',
        ),
    ]
