# Generated by Django 6.0.3 on 2026-03-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delete_instagrampost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(help_text='Nome do membro da equipa', max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordem'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(help_text='Foto do membro', upload_to='team/', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(help_text='Cargo / Função', max_length=255, verbose_name='função'),
        ),
    ]
