# Generated by Django 6.0.4 on 2026-05-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_teammember_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'membro da equipa', 'verbose_name_plural': 'membros da equipa'},
        ),
    ]
