# Generated by Django 6.0.4 on 2026-05-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_teammember_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(help_text='Shortcode único do post no Instagram', max_length=50, unique=True, verbose_name='ID do post')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL da imagem')),
                ('caption', models.TextField(blank=True, verbose_name='legenda')),
                ('permalink', models.URLField(max_length=300, verbose_name='link do post')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'post do Instagram',
                'verbose_name_plural': 'posts do Instagram',
                'ordering': ['-posted_at', '-pk'],
            },
        ),
    ]
