# Generated by Django 6.0.5 on 2026-05-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_instagrampost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL da imagem'),
        ),
    ]
