# Generated by Django 6.0.5 on 2026-05-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_instagrampost_image_url_blank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagrampost',
            options={'ordering': ['sort_order', '-posted_at', '-pk'], 'verbose_name': 'post do Instagram', 'verbose_name_plural': 'posts do Instagram'},
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Menor = primeiro', verbose_name='ordem'),
        ),
    ]
