# Generated by Django 6.0.4 on 2026-05-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='payment_timeout_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Após este tempo, o pagamento e a encomenda são cancelados automaticamente. Defina 0 para desativar.', verbose_name='tempo limite para pagamento (minutos)'),
        ),
    ]
