# Generated by Django 6.0.3 on 2026-03-03 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='blog/covers/')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Lista de tags, ex: ["receitas", "bio"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'artigo do blog',
                'verbose_name_plural': 'artigos do blog',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='recipes/covers/')),
                ('prep_time', models.PositiveIntegerField(help_text='Tempo de preparação em minutos')),
                ('cook_time', models.PositiveIntegerField(blank=True, help_text='Tempo de cozedura em minutos', null=True)),
                ('servings', models.PositiveIntegerField(default=4)),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], default='medium', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags para filtragem, ex: ["vegetariano", "sem glúten"]')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_products', models.ManyToManyField(blank=True, help_text='Produtos relacionados (comprar ingredientes)', related_name='recipes', to='catalog.product')),
            ],
            options={
                'verbose_name': 'receita',
                'verbose_name_plural': 'receitas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'PT'), ('en', 'EN'), ('fr', 'FR')], max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField(blank=True, help_text='Resumo curto para listagens')),
                ('content', models.TextField(help_text='Conteúdo do artigo (HTML)')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.blogpost')),
            ],
            options={
                'verbose_name': 'tradução de artigo',
                'verbose_name_plural': 'traduções de artigo',
                'unique_together': {('blog_post', 'language')},
            },
        ),
        migrations.CreateModel(
            name='RecipeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'PT'), ('en', 'EN'), ('fr', 'FR')], max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descrição curta')),
                ('ingredients', models.JSONField(default=list, help_text='Lista de ingredientes: [{"name": "...", "amount": "...", "unit": "..."}]')),
                ('instructions', models.TextField(help_text='Instruções de preparação (HTML)')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.recipe')),
            ],
            options={
                'verbose_name': 'tradução de receita',
                'verbose_name_plural': 'traduções de receita',
                'unique_together': {('recipe', 'language')},
            },
        ),
    ]
