# Generated by Django 6.0.3 on 2026-03-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_recipetranslation_instructions_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposttranslation',
            name='language',
            field=models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('fr', 'Francês')], max_length=2),
        ),
        migrations.AlterField(
            model_name='recipetranslation',
            name='language',
            field=models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('fr', 'Francês')], max_length=2),
        ),
    ]
