# Generated by Django 6.0.3 on 2026-03-17 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_category_image_alter_category_is_active_and_more'),
        ('content', '0003_alter_blogposttranslation_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='blog/covers/', verbose_name='imagem de capa'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='publicado'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publicado em'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Lista de tags, ex: ["receitas", "bio"]', verbose_name='etiquetas'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='blogposttranslation',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.blogpost', verbose_name='artigo do blog'),
        ),
        migrations.AlterField(
            model_name='blogposttranslation',
            name='content',
            field=models.TextField(help_text='Conteúdo do artigo (HTML)', verbose_name='conteúdo'),
        ),
        migrations.AlterField(
            model_name='blogposttranslation',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Resumo curto para listagens', verbose_name='resumo'),
        ),
        migrations.AlterField(
            model_name='blogposttranslation',
            name='language',
            field=models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('fr', 'Francês')], max_length=2, verbose_name='idioma'),
        ),
        migrations.AlterField(
            model_name='blogposttranslation',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='meta descrição'),
        ),
        migrations.AlterField(
            model_name='blogposttranslation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(blank=True, help_text='Tempo de cozedura em minutos', null=True, verbose_name='tempo de cozedura'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='recipes/covers/', verbose_name='imagem de capa'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], default='medium', max_length=10, verbose_name='dificuldade'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='publicado'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(help_text='Tempo de preparação em minutos', verbose_name='tempo de preparação'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='Produtos relacionados (comprar ingredientes)', related_name='recipes', to='catalog.product', verbose_name='produtos relacionados'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(default=4, verbose_name='doses'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags para filtragem, ex: ["vegetariano", "sem glúten"]', verbose_name='etiquetas'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='recipetranslation',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição curta', verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='recipetranslation',
            name='ingredients',
            field=models.JSONField(default=list, help_text='Lista de ingredientes: ["200g farinha", "2 ovos", ...]', verbose_name='ingredientes'),
        ),
        migrations.AlterField(
            model_name='recipetranslation',
            name='instructions',
            field=models.JSONField(default=list, help_text='Lista de passos de preparação: ["Pré-aquecer o forno...", "Misturar..."]', verbose_name='instruções'),
        ),
        migrations.AlterField(
            model_name='recipetranslation',
            name='language',
            field=models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('fr', 'Francês')], max_length=2, verbose_name='idioma'),
        ),
        migrations.AlterField(
            model_name='recipetranslation',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='meta descrição'),
        ),
        migrations.AlterField(
            model_name='recipetranslation',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.recipe', verbose_name='receita'),
        ),
        migrations.AlterField(
            model_name='recipetranslation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='título'),
        ),
    ]
