# Generated by Django 6.0.4 on 2026-05-05 15:43

from django.db import migrations, models


def backfill_recipe_content(apps, schema_editor):
    del schema_editor
    RecipeTranslation = apps.get_model('content', 'RecipeTranslation')
    for translation in RecipeTranslation.objects.all():
        instructions = translation.instructions or []
        if translation.content or not instructions:
            continue
        translation.content = '\n\n'.join(str(step).strip() for step in instructions if str(step).strip())
        translation.save(update_fields=['content'])


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_content_tag_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipetranslation',
            name='content',
            field=models.TextField(blank=True, help_text='Conteúdo da receita em Markdown', verbose_name='conteúdo'),
        ),
        migrations.RunPython(backfill_recipe_content, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='blogposttranslation',
            name='content',
            field=models.TextField(help_text='Conteúdo do artigo em Markdown', verbose_name='conteúdo'),
        ),
        migrations.AlterField(
            model_name='blogposttranslation',
            name='excerpt',
            field=models.TextField(help_text='Resumo curto para listagens', verbose_name='resumo'),
        ),
        migrations.AlterField(
            model_name='recipetranslation',
            name='description',
            field=models.TextField(help_text='Resumo curto', verbose_name='resumo'),
        ),
    ]
