# Generated by Django 6.0.4 on 2026-05-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_status_in_transit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='local de levantamento'),
        ),
    ]
