# Generated by Django 6.0.4 on 2026-05-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_pickup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_state',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='estado do pagamento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('preparing', 'Em Preparação'), ('ready', 'Pronta'), ('in_transit', 'Em Transporte'), ('delivered', 'Entregue'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='estado'),
        ),
    ]
