# Generated by Django 6.0.4 on 2026-05-05 14:55

from django.db import migrations, models


def migrate_confirmed_orders_to_pending(apps, schema_editor):
    del schema_editor
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(status='confirmed').update(status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_payment_state'),
    ]

    operations = [
        migrations.RunPython(migrate_confirmed_orders_to_pending, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('preparing', 'Em Preparação'), ('ready', 'Pronta para levantamento'), ('in_transit', 'Em trânsito'), ('delivered', 'Entregue'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='estado'),
        ),
    ]
