# Generated by Django 6.0.4 on 2026-05-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nif',
            field=models.CharField(blank=True, max_length=9, verbose_name='NIF'),
        ),
    ]
