# Generated by Django 6.0.3 on 2026-03-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Levantamento na loja, Entrega ao domicílio', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'método de entrega',
                'verbose_name_plural': 'métodos de entrega',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Loja Braga, Loja Guimarães', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'localização',
                'verbose_name_plural': 'localizações',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_locations',
        ),
        migrations.AddField(
            model_name='product',
            name='available_locations',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.location', verbose_name='localizações disponíveis'),
        ),
    ]
