# Generated by Django 6.0.3 on 2026-03-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured_message',
            field=models.CharField(blank=True, help_text='Mensagem opcional exibida em banner no cartão desta categoria especial.', max_length=200, verbose_name='mensagem de destaque'),
        ),
    ]
