# Generated by Django 6.0.3 on 2026-03-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_featured_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight_grams',
        ),
        migrations.AddField(
            model_name='product',
            name='bio_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='código bio (EU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='ingredientes'),
        ),
        migrations.AddField(
            model_name='product',
            name='modifiers',
            field=models.CharField(blank=True, help_text='Ex: Sem glúten, Soja, Frutos secos', max_length=255, verbose_name='modificadores / alergénicos'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='quantidade unitária'),
        ),
    ]
