# Generated by Django 6.0.3 on 2026-03-17 14:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_category_image_alter_category_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bio_code',
            field=models.CharField(help_text='Ex: PT-BIO-03', max_length=50, verbose_name='código bio (EU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(help_text='Lista completa de ingredientes do produto.', verbose_name='ingredientes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modifiers',
            field=models.CharField(help_text='Ex: Contém glúten, soja, frutos secos', max_length=255, verbose_name='alergénicos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_quantity',
            field=models.DecimalField(decimal_places=2, help_text='Peso líquido do produto em gramas.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='gramagem (g)'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='description',
            field=models.TextField(verbose_name='descrição'),
        ),
    ]
