# Generated by Django 6.0.4 on 2026-05-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_catalog_pt_first_and_external_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='deliverymethod',
            options={'verbose_name': 'método de entrega', 'verbose_name_plural': 'métodos de entrega'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'localização', 'verbose_name_plural': 'localizações'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_highlight', 'name', 'pk'], 'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
        migrations.AlterField(
            model_name='category',
            name='featured_message',
            field=models.CharField(blank=True, max_length=200, verbose_name='mensagem de destaque'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='especial'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='location',
            name='pickup_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Horário de levantamento por dia da semana. Ex: {"mon": "09:00-18:00"}.', verbose_name='horário de levantamento'),
        ),
        migrations.AlterField(
            model_name='location',
            name='pickup_location_code',
            field=models.CharField(blank=True, choices=[('braga', 'Braga'), ('guimaraes', 'Guimarães')], help_text='Liga a localização a uma opção fixa de levantamento usada no checkout.', max_length=20, verbose_name='código de levantamento'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allow_shipping',
            field=models.BooleanField(default=False, verbose_name='envio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bio_code',
            field=models.CharField(max_length=50, verbose_name='código bio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=120, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_preview',
            field=models.BooleanField(default=False, verbose_name='pré-visualização'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pickup_locations',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.location', verbose_name='localizações de recolha'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(max_length=80, verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='allergens',
            field=models.CharField(max_length=255, verbose_name='alergénicos'),
        ),
    ]
