# Generated by Django 6.0.4 on 2026-05-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_category_options_alter_deliverymethod_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allow_pickup',
            field=models.BooleanField(default=False, verbose_name='recolha'),
        ),
    ]
