# Generated by Django 6.0.4 on 2026-05-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_product_allow_pickup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverymethod',
            name='description',
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='estimated_delivery_time',
            field=models.CharField(blank=True, max_length=120, verbose_name='tempo estimado de entrega'),
        ),
        migrations.AlterField(
            model_name='location',
            name='pickup_location_code',
            field=models.CharField(blank=True, help_text='Identificador interno gerado automaticamente a partir do nome do local.', max_length=60, verbose_name='código de levantamento'),
        ),
    ]
