# Generated by Django 6.0.4 on 2026-05-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_remove_deliverymethod_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymethod',
            name='name',
            field=models.CharField(help_text='Ex: CTT Express, DHL', max_length=100, verbose_name='nome'),
        ),
    ]
