# Generated by Django 6.0.3 on 2026-03-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('fr', 'Francês')], default='pt', max_length=2),
        ),
    ]
