# Generated by Django 6.0.4 on 2026-05-04 21:06

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_address_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staff',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
