# Generated by Django 6.0.4 on 2026-05-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customeraccount_staffaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffaccount',
            options={'verbose_name': 'equipa', 'verbose_name_plural': 'equipa'},
        ),
    ]
