events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    map $http_x_forwarded_proto $proxy_forwarded_proto {
        default $http_x_forwarded_proto;
        ''      $scheme;
    }

    sendfile on;
    keepalive_timeout 65;
    client_max_body_size 20M;

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript image/svg+xml;

    # Shared upstreams
    upstream django_website {
        server django_website:8000;
    }

    upstream django_shop {
        server django_shop:8000;
    }

    upstream django_admin {
        server django_admin:8000;
    }

    # Shared proxy settings.
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Proto $proxy_forwarded_proto;
    proxy_http_version 1.1;
    proxy_redirect off;

    include /etc/nginx/conf.d/*.conf;
}
