# Generated by Django 6.0.2 on 2026-02-27 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('multibanco', 'Multibanco'), ('mbway', 'MB WAY'), ('credit_card', 'Cartão de Crédito')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhado'), ('expired', 'Expirado'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ifthenpay_request_id', models.CharField(blank=True, max_length=255)),
                ('mb_entity', models.CharField(blank=True, max_length=10)),
                ('mb_reference', models.CharField(blank=True, max_length=20)),
                ('mbway_phone', models.CharField(blank=True, max_length=20)),
                ('mbway_transaction_id', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
            },
        ),
        migrations.CreateModel(
            name='PaymentCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.JSONField()),
                ('ip_address', models.GenericIPAddressField()),
                ('is_valid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callbacks', to='payments.payment')),
            ],
            options={
                'verbose_name': 'callback de pagamento',
                'verbose_name_plural': 'callbacks de pagamento',
            },
        ),
    ]
