# Generated by Django 6.0.3 on 2026-03-17 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_created_at_alter_order_email_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expira em'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ifthenpay_request_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID do pedido Ifthenpay'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mb_entity',
            field=models.CharField(blank=True, max_length=10, verbose_name='entidade MB'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mb_reference',
            field=models.CharField(blank=True, max_length=20, verbose_name='referência MB'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mbway_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone MB WAY'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mbway_transaction_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID da transação MB WAY'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('multibanco', 'Multibanco'), ('mbway', 'MB WAY'), ('credit_card', 'Cartão de Crédito')], max_length=20, verbose_name='método'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='encomenda'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pago em'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhado'), ('expired', 'Expirado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='paymentcallback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='paymentcallback',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='endereço IP'),
        ),
        migrations.AlterField(
            model_name='paymentcallback',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='válido'),
        ),
        migrations.AlterField(
            model_name='paymentcallback',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callbacks', to='payments.payment', verbose_name='pagamento'),
        ),
        migrations.AlterField(
            model_name='paymentcallback',
            name='raw_payload',
            field=models.JSONField(verbose_name='carga útil bruta'),
        ),
    ]
