# Generated by Django 6.0.3 on 2026-03-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_legacy_provider_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL de checkout'),
        ),
    ]
