# Generated by Django 6.0.4 on 2026-05-05 14:55

from django.db import migrations, models


def migrate_legacy_payment_statuses(apps, schema_editor):
    del schema_editor
    Payment = apps.get_model('payments', 'Payment')
    Payment.objects.filter(status='paid').update(status='confirmed')
    Payment.objects.filter(status__in=['failed', 'expired']).update(status='cancelled')


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_drop_paymentcallback_and_reduce_methods'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_payment_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='estado'),
        ),
    ]
